config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'

  get 'alchup/:id' => 'pages#alchup', as: :alchup
  get 'ruta/:id' => 'pages#route', as: :route
  get 'que-son' => 'pages#what', as: :what
  get 'el-pueblo' => 'pages#town', as: :town
  get 'cookies' => 'pages#cookies', as: :cookies
  devise_for :admins

  devise_scope :admin do
    authenticated :admin do
      root 'tanks#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get 'order_by_title' => 'tanks#order_by_title'
  get 'order_by_id' =>    'tanks#order_by_id'
  resources :tanks do
    resources :photos, only: [:create, :destroy, :new]
  end
  resources :qr, only: [:show]
end

app/models/admin.rb
class Admin < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :recoverable,
  devise :database_authenticatable,:rememberable, :trackable

 

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :tank
  has_attached_file :image, :styles => { :medium => "415x230#", :thumb => "115x85#", :large => "1350x750#" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/redirection.rb
class Redirection < ActiveRecord::Base
end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :tanks
  def to_s
    title
  end
end

app/models/tank.rb
class Tank < ActiveRecord::Base
  validates :title, presence:true
  has_many :photos
  belongs_to :route

  def main_photo(size=:thumb)
    if(photos.size > 0)
      photos.first.image.url(size)
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout "public"
  def index
    @tanks = Tank.all.order(:title)
    @routes = Route.all
  end

  def alchup
    @tank = Tank.find(params[:id])
    @other = Tank.limit(3).order("RANDOM()")
  end

  def route
    @route = Route.find(params[:id])
  end

  def town
  end

  def what
  end

  def cookies
  end
end

app/controllers/photos_controller.rb
class PhotosController < AdminController
  def new
    tank = Tank.find(params[:tank_id])
    @photo = Photo.new(tank: tank)
  end

  def create
    tank = Tank.find(params[:tank_id])
    tank.photos.create(photo_params)
    redirect_to tank_path(tank)
  end

  def destroy
    tank = Tank.find(params[:tank_id])
    tank.photos.find(params[:id]).destroy
    redirect_to tank_path(tank)
  end

  private 
    def photo_params
      params.require(:photo).permit(:image)
    end
end

app/controllers/qr_controller.rb
class QrController < ApplicationController
  def show
    redirection = Redirection.find_by(id: params[:id])
    if redirection and redirection.target_url
      redirect_to redirection.target_url
    else
      render :text => 'qr without redirect'
    end
  end
end

app/controllers/tanks_controller.rb
class TanksController < AdminController
  def new
    @tank = Tank.new
  end

  def create
    @tank = Tank.new(tank_params)
    if @tank.save
      redirect_to @tank
    else
      render 'new'
    end
  end

  def show
    @tank = Tank.find(params[:id])
  end

  def index
    @tanks = Tank.all.order(params[:sort])
  end

  def edit
    @tank = Tank.find(params[:id])
  end

  def update
    @tank = Tank.find(params[:id])
    if @tank.update_attributes(tank_params)
      redirect_to @tank
    else
      render 'edit'
    end
  end

  def destroy
    Tank.find(params[:id]).destroy
    redirect_to tanks_url
  end

  def order_by_title
    @tanks = Tank.all.order(:title)
    render 'index' 
  end

  def order_by_id
    @tanks = Tank.all.order(:id)
    render 'index'
  end

  private
    def tank_params
      params.require(:tank).permit(:title, :description, :latitude, :longitude, :notes, :route_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def routes_options()
    Route.all.collect {|a| [a.title, a.id]}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alchups</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= csrf_meta_tags %>
  <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyD0Q5qmrEu6MCrOKn8qECqg_0sAqF1qw4s">
  </script>
  <%= favicon_link_tag 'favicon.png', type: 'image/png' %>
  <%= javascript_include_tag "application" %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
        <a class="navbar-brand" href="/tanks">Alchups</a>
      </div>
      <% if admin_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">Página pública</a></li>
        <li><%= link_to "Salir", destroy_admin_session_path, :method => :delete %></li>
      </ul>
      <% end %>
  </div>
</nav>

<div class="container">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
</div>

</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  <title><%= yield(:title) %> | Alchups de San Esteban de Litera</title>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,600' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,700,300' rel='stylesheet' type='text/css'>
  <%= favicon_link_tag 'favicon.png', type: 'image/png' %>
  <%= stylesheet_link_tag 'public', media: 'all'%>
  <%= csrf_meta_tags %>

  <!-- OpenGraph and META TAGS -->
  <meta name="description" content="Descubre los Aljibes de San Esteban de la Litera" />
  <meta property="og:type" content="website">
  <meta property="og:title" content="Alchups de San Esteban de Litera">
  <meta property="og:description" content="Descubre los Aljibes de San Esteban de la Litera">
  <meta property="og:url" content="<%=request.original_url%>">
  <meta property="og:site_name" content="Alchups.com">
  <meta property="og:image" content="<%= image_url("photo-share-social.png") %>">
</head>
<body>
  <div class="site">
    <header class="main-header">
      <div class="wrapper">
        <nav class="main-menu">
          <ul>
            <li><%= link_to "¿Qué son los Alchups?", what_path %></li>
            <li><%= link_to "El pueblo", town_path %></li>
          </ul>
        </nav>
      </div>
      <div class="site-description">
      <%= yield :header %>
      </div><!-- .site-description -->
    </header>

    <main>
      <%= yield %>
    </main>

    <footer>
      <div class="main-footer">
        <div class="wrapper">
          <div class="col">
            <%=link_to image_tag("logo-white.png", :alt=>"Logotipo de Alchups"), root_path %>
          </div><!-- .col -->
          <div class="col">
            <ul>
              <li><%= link_to "De los lavaderos a las Forcas", route_path(1) %></li>
              <li><%= link_to "De Perera a la Heredad", route_path(2) %></li>
              <li><%= link_to "¿Qué son los Alchups?", what_path %></a></li>
              <li><%= link_to "El pueblo", town_path %></li>
              <li><%= link_to "Web municipal", "http://www.sanestebandelitera.es/" %></li>
              <li><%= link_to "Email: sanesteban@lalitera.org", "mailto:sanesteban@lalitera.org" %></li>
            </ul>
          </div><!-- .col -->
          <div class="col logos">
            <a href="http://www.dphuesca.es/"><%=image_tag "logo-dph.png", :alt=>"Logotipo de la Diputación Provincial de Huesca" %></a>
            <a href="http://www.sanestebandelitera.es/"><%=image_tag "logo-sel.png", :alt=>"Logotipo de San Esteban de la Litera" %></a>
          </div><!-- .col -->
        </div><!-- .wrapper -->
      </div><!-- .main-footer -->
      <div class="main-footer-project">
        <div class="wrapper">
          <strong>Alchups</strong> es un proyecto <a href="https://github.com/bierasolutions/alchups">open source</a><br /> <%=image_tag "logo-github.png", :alt=>"GitHub Logo" %> <br /> A tu disposicion en <a href="https://github.com/bierasolutions/alchups">GitHub</a>.
        </div><!-- .wrapper -->
      </div><!-- .main-footer-project -->
    </footer>
  </div><!-- .site -->
  <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyD0Q5qmrEu6MCrOKn8qECqg_0sAqF1qw4s">
  </script>
  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/pages/alchup.html.erb
<% content_for :title do %>
<%=@tank.title%>
<% end %>
<% content_for :header do %>
  <div class="wrapper">
          <h2><%= link_to image_tag("logo.svg", :width=>"295", :height=>"32"), root_path%></h2><br />
          <p>Descubre los Aljibes de San Esteban de la Litera</p>
        </div><!-- .wrapper -->
        <div class="single-title">
          <h1><%=@tank.title%></h1>
        </div>
<% end %>

<div class="wrapper">
      <% unless @tank.photos.empty? %>
        <div class="single-image">
          <%= image_tag @tank.main_photo(:large), id: 'header_img', :alt => @tank.title %>
          <div class="image-selector">
            <% @tank.photos.each do |photo|%>
            <a href="<%=photo.image.url(:large)%>" class="item"><%= image_tag photo.image.url(:thumb) %></a>
            <%end%>
          </div>
        </div><!-- .single-image -->

      <%end%>

        <div class="single-content">
          <%if @tank.route%>
            <div class="belong-route"><span class="label ruta<%=@tank.route.id%>"><%=link_to raw('Pertenece a<br />ruta <strong>1</strong> &gt;') ,route_path(@tank.route)%></span></div>
          <%end%>
          <div class="content" id="description" data-latitude="<%= @tank.latitude %>" data-longitude="<%= @tank.longitude %>">
            <%=simple_format (@tank.description)%>
            <br/><br/>
            <div id="map-canvas" class="map">
            </div>
          </div>
        </div><!-- .single-content -->


        <div class="close-alchups">
          <h2>Otros aljibes</h2>
          <div class="close-alchups-items">
            <%@other.each do |tank|%>
            <a href="<%=alchup_path(tank)%>" class="item">
              <h4><%=tank.title%><i class="icon-arrow-right3"></i></h4>
              <img src="<%=tank.main_photo(:medium)%>" alt="<%=tank.title%>">
            </a>
            <%end%>
          </div>
        </div><!-- .close-alchups-->

        <div class="routes">
          <div class="route">
            <span class="label">Ruta <strong>1</strong></span>
            <h2>De los lavaderos a las Forcas</h2>
            <p><%=image_tag "home-ruta1.png", :alt=>"Fotografías de la Ruta 1"%></p>
            <a href="<%=route_path(1)%>" class="btn primary">Quiero conocer esta ruta <span class="arrow">›</span></a>
          </div><!-- .route -->
          <div class="route">
            <span class="label">Ruta <strong>2</strong></span>
            <h2>De Perera a la Heredad</h2>
            <p><%=image_tag "home-ruta2.png", :alt=>"Fotografías de la Ruta 2"%></p>
            <a href="<%=route_path(2)%>" class="btn primary">Quiero conocer esta ruta <span class="arrow">›</span></a>
          </div><!-- .route -->
        </div>  
      </div><!-- .wrapper -->

app/views/pages/cookies.html.erb
<% content_for :title do %>
Política de cookies
<% end %>
<% content_for :header do %>
  <div class="wrapper">
    <h2><%= link_to image_tag("logo.svg", :width=>"295", :height=>"32"), root_path%></h2><br />
    <p>Descubre los Aljibes de San Esteban de la Litera</p>
  </div><!-- .wrapper -->
  <div class="single-title">
    <h1>Política de cookies</h1>
  </div>
<% end %>
<div class="wrapper">
 <div class="single-content">
  <div class="content">
    <p>En cumplimiento de la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y Comercio Electrónico, te informamos de que este sitio web, al igual que la mayoría de los sitios en Internet, usa Cookies para mejorar y optimizar la experiencia del usuario.</p>
    <p>A continuación encontrarás información detallada sobre qué son las Cookies, qué tipología utiliza este sitio web, cómo cambiar la configuración de tus cookies, y qué ocurre si deshabitas las Cookies.</p>
    <h2>¿Qué son las Cookies?</h2>
    <p>Una cookie es un pequeño archivo que se descarga en el equipo del usuario con la finalidad de almacenar datos, los cuales podrán ser actualizados y recuperados por la entidad responsable de su instalación.</p>
    <h2>¿Qué tipo de Cookies utiliza esta página web?</h2>
    <p>A continuación se muestra una tabla con las Cookies utilizadas en este sitio web:</p>
    <table border="1">
      <thead>
      <tr>
      <th style="width:20%">Tipo de Cookie</th>
      <th>Descripción</th>
      <th>Proveedor</th>
      </tr>
      </thead>
      <tbody>
      <tr>
      <td>Cookies de sesión</td>
      <td><small>Cookies temporales que permanecen en el archivo de cookies de tu navegador mientras estás en nuestra página web. Es decir, están activas mientras dura la visita a este sitio web y por tanto son borradas de tu ordenador al abandonarlo.</small></td>
      <td>Propias</td>
      </tr>
      <tr>
      <td>Cookies de análisis</td>
      <td><small>Cookies que permiten cuantificar el número de usuarios y así realizar la medición y análisis estadístico de la utilización que hacen los usuarios del servicio ofertado.</small></td>
      <td>Google Analytics</td>
      </tr>
      </tbody>
    </table>
    <h2>¿Cómo puedes configurar tus Cookies?</h2>
    <p>Al navegar y continuar en nuestro sitio web, estarás consintiendo el uso de las Cookies en las condiciones contenidas en la presente Política de Cookies. Como usuario, tienes la posibilidad de ejercer tu derecho a bloquear, eliminar y rechazar el uso de Cookies, en todo momento, modificando las opciones de tu navegador.</p>
    <p>Por ejemplo:</p>
    <ol>
      <li>Internet Explorer: Herramientas &gt; Opciones de Internet &gt; Privacidad &gt; Configuración. Para más información, puedes consultar el soporte de Microsoft o la Ayuda del navegador.</li>
      <li>Mozilla Firefox: Herramientas &gt; Opciones &gt; Privacidad &gt; Historial &gt; Configuración Personalizada. Para más información, puedes consultar el soporte de Mozilla o la Ayuda del navegador.</li>
      <li>Google Chrome: Configuración &gt; Mostrar opciones avanzadas &gt; Privacidad -&gt; Configuración de contenido. Para más información, puedes consultar el soporte de Google o la Ayuda del navegador.</li>
      <li>Safari: Preferencias &gt; Seguridad. Para más información, puedes consultar el soporte de Apple o la Ayuda del navegador.</li>
      <li>Opera: Configuración &gt; Opciones &gt; Avanzado &gt; Cookies Para más información, puedes consultar el soporte de Opera o la Ayuda del navegador.</li>
    </ol>
    <p>Si usas otro navegador distinto a los anteriores, consulta su política de instalación, uso y bloqueo de cookies.</p>
    <h2>¿Qué ocurre si se deshabilitan las Cookies?</h2>
    <p>Algunas funcionalidades de los Servicios o áreas de este sitio web podrían no funcionar correctamente.</p>
    <h2>¿Actualizamos nuestra política de Cookies?</h2>
    <p>Es posible que actualicemos la política de Cookies de nuestra página web, por ello, nuestros abogados nos piden que te recomendamos revisar esta política cada vez que accedas a nuestro sitio web, con el objetivo de estar adecuadamente informado sobre cómo y para que úsamos las Cookies.</p>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<% content_for :title do %>
Bienvenido
<% end %>
<% content_for :header do %>
  <h1><%= link_to image_tag("logo.svg", :width=>"295", :height=>"32"), root_path%></h1><br />
  <p>Descubre los Aljibes de San Esteban de la Litera</p>
<% end %>


<div class="main-map" id="home">
      <div id="map-canvas" style="height: 620px;"></div>
</div><!-- main-map -->
<div class="main-description">
  <div class="wrapper">
    <em><strong>Alchup</strong></em> es la transcripción fonética empleada en la Litera del vocablo <em><strong>aljub</strong></em> utilizado ya en los documentos redactados en castellano en San Esteban de Litera en el 1579. Esta palabra sigue viva en el catalán actual y designa un depósito excavado en la roca o hecho con piedra y cubierto con bóveda para recoger y almacenar el agua de lluvia, aunque en la comarca de La Litera son depósitos sin esta cubierta. Tiene su equivalente al aljibe castellano, o cisterna, que es el depósito subterráneo donde se recoge y conserva el agua. Los más antiguos se construyeron entre los años 714 y 1149 de nuestra era, ya que junto a algunos aparecen fragmentos de cerámica islámica procedentes de su limpieza. Se sabe, por la documentación notarial conservada, que muchos ya existían en la zona de Albelda a mediados del siglo XVI. Posteriormente se siguieron construyendo, ampliando o reformando hasta finales del siglo XIX, como es el caso del gran alchup de Perera, que se construyó en el año 1579 al encargar el concejo municipal, unir en uno solo dos de ya existentes. Definitivamente, se amplió en el año 1892 hasta alcanzar una longitud de 21,37 m.
  </div><!-- .wrapper -->
</div><!-- main-description -->

<div class="wrapper">
  <div class="routes">
    <div class="route">
      <span class="label">Ruta <strong>1</strong></span>
      <h2>De los lavaderos a las Forcas</h2>
      <p><%=image_tag "home-ruta1.png", :alt=>"Fotografías de la Ruta 1"%></p>
      <a href="<%=route_path(1)%>" class="btn primary">Quiero conocer esta ruta <span class="arrow">›</span></a>
    </div><!-- .route -->
    <div class="route">
      <span class="label">Ruta <strong>2</strong></span>
      <h2>De Perera a la Heredad</h2>
      <p><%=image_tag "home-ruta2.png", :alt=>"Fotografías de la Ruta 2"%></p>
      <a href="<%=route_path(2)%>" class="btn primary">Quiero conocer esta ruta <span class="arrow">›</span></a>
    </div><!-- .route -->
  </div>  
</div><!-- .wrapper -->

<div class="wrapper">
  <div class="aljibes">
    <h2>Además de las rutas, puedes conocer cada uno de los <%= @tanks.size %> aljibes localizados</h2>
    <ol class="aljibes-list" id="alchups">
      <% @tanks.each do |tank| %>
        <li data-latitude="<%= tank.latitude %>" data-longitude="<%= tank.longitude %>" data-img="<%= tank.main_photo%>">
          <%=link_to tank.title, alchup_path(tank) %>
        </li>
      <% end %>
    </ol><!-- .aljibes-list -->
  </div>
</div><!-- .wrapper -->

app/views/pages/route.html.erb
<% content_for :title do %>
Ruta <%=@route.title%>
<% end %>
<% content_for :header do %>
  <div class="wrapper">
    <h2><%= link_to image_tag("logo.svg", :width=>"295", :height=>"32"), root_path%></h2><br />
    <p>Descubre los Aljibes de San Esteban de la Litera</p>
  </div><!-- .wrapper -->
  <div class="single-title ruta ruta<%=@route.id%>">
    <span class="label">Ruta <strong><%=@route.id%></strong></span>
    <h1 id="route" data-id="<%=@route.id%>"><%=@route.title%></h1>
  </div>
<% end %>
<div class="single-ruta-image">

  <%= image_tag "ruta#{@route.id}.png", :alt=>"Imagen previa de la ruta 1" %>
</div><!-- .single-ruta-image -->
<div class="wrapper">
<div class="single-content">
          
          <div class="content">
            <div id="map-canvas" class="map">
              
            </div>
            <p>
            <%=simple_format (@route.description)%>
            </p>
            <h2>Descárgate:</h2>
            <ul>
              <li><%= link_to 'La ruta en KML', "/downloads/ruta#{@route.id}.kml" %>.</li>
              <li><%= link_to 'El panel informativo de la ruta en PDF', "/downloads/panel#{@route.id}.pdf"%>.</li>
            </ul>
            <h2>Dificultad:</h2>
            <p>
            Dificultad Media. Ruta con una dificultad no muy elevada.
            </p>

            <h2>Ruta indicada para:</h2>
            <ul>
            <li>Senderismo con niños o en familia.</li>
            <li>Senderismo.</li>
            <li>Bicicleta de montaña.</li>
            <li>A caballo.</li>
            </ul>

            <h2>A tener en cuenta:</h2>
            <ul>
            <li>No olvides planificar tu ruta (horario, metereología, etc.) y llevar el equipamiento necesario (calzado y ropa adecuada, agua, etc.).</li>
            <li>Respeta la fauna y flora, no arranques las plantas ni asustes a los animales.</li>
            <li>Disfruta del camino, intentando identificar flora y fauna, y de los paisajes repletos de contrastes que encontrarás.</li>
            <li>No olvides tus prismáticos y tu cámara de fotos.</li>
            <li>No tires basura. Queremos ver tu pisada no tu huella.</li>
            <li>No hagas fuego. Respeta los caminos y senderos.</li>
            <li>Cruza las tierras de cultivo por los senderos y nunca por la zona sembrada.</li>
            <li>Sigue y respeta las señales. En época de caza respeta las acotaciones.</li>
            <li>Comunica rápidamente cualquier incidencia al teléfono de emergencia <b>112</b></li>.
            </ul>
            <% unless @route.tanks.empty?%> 
            <div class="single-image">
              <%= image_tag @route.tanks.first.main_photo(:large), id: 'header_img'%>
              <div class="image-selector">
                <% @route.tanks.each do |tank|%>
                <a href="<%=tank.main_photo(:large)%>" class="item"><%= image_tag tank.main_photo(:thumb) %></a>
                <%end%>
              </div>
            </div><!-- .single-image -->
          </div>
          <%end%>
        </div><!-- .single-content -->

  <div class="aljibes">
    <h2>Esta ruta tiene <%= @route.tanks.size %> aljibes localizados</h2>
    <ol class="aljibes-list" id="alchups">
      <% @route.tanks.each do |tank| %>
        <li data-latitude="<%= tank.latitude %>" data-longitude="<%= tank.longitude %>" data-img="<%= tank.main_photo%>">
          <%=link_to tank.title, alchup_path(tank) %>
        </li>
      <% end %>
    </ol><!-- .aljibes-list -->
  </div>
</div><!-- .wrapper -->

app/views/photos/new.html.erb
<h2>Añadir foto a <%= @photo.tank.title %></h2>
<div class="row">
  <div class="well bs-component">
    <%= form_for @photo, :url => tank_photos_path(@photo.tank), :html => { :multipart => true, :class => "form-horizontal" } do |form| %>
      <fieldset>
        <div class="form-group">
          <%= form.label :image, :class => "col-lg-2 control-label" %>
          <div class="col-lg-10">
          <%= form.file_field :image, :class => "form-control" %>
          </div>
        </div>
        
        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <input type="submit" class="btn btn-primary">
            <%= link_to "Volver atrás", tank_path(@photo.tank), class: "btn btn-default" %>
          </div>
        </div>  
      </fieldset>
    <% end %>
  </div>
</div>

app/views/tanks/edit.html.erb
<h1>Editar Aljibe</h1>
<div class="row">
<%= link_to "Subir foto", new_tank_photo_path(@tank) %>
  <div class="well bs-component">
    <%= form_for @tank, :html => {:class => "form-horizontal"} do |f| %>
      <fieldset>
        <%= render partial: "form", locals: {f: f} %>      
        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <%= f.submit "Guardar cambios", class: "btn btn-primary" %>
            <%= link_to "Volver atrás", tank_path(@tank), class: "btn btn-default" %>
          </div>
        </div>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/tanks/index.html.erb
<div id="tanksIndex">
	<h2>Lista de aljibes</h2>
	<div class="row">
	  <div class="col-xs-12 col-md-6">
	  <p>
		<%= link_to "Nuevo Aljibe", new_tank_path, class: "btn btn-success btn-sm" %>
		</p>
		<%= link_to "Ordenar(A-Z)", order_by_title_path, class: "btn btn-primary btn-sm" %> 
		<%= link_to "Ordenar por ID", order_by_id_path, class: "btn btn-primary btn-sm" %>
		<table class="table table-striped" id="alchups">
			<tr>
				<th>#</th><th>Nombre</th><th></th><th></th>
			</tr>
			<% @tanks.each do |tank| %>

				
				<tr data-latitude="<%= tank.latitude %>" data-longitude="<%= tank.longitude %>"
					data-iden = "<%= tank.id %>" data-title = "<%= tank.title %>">
					<td><%= link_to tank.id, tank %></td>
					<td><%= link_to tank.title, tank %></td>
					<td><%= link_to "editar", edit_tank_path(tank) %></td>
					<td><%= link_to "borrar",tank, method: :delete, data: {confirm: "¿Estas seguro?"} %></td>
				</tr>
			<% end %>
		</table>
		 
	  </div>
	  <div class="col-xs-6 col-md-6" id="map-canvas" style="height: 500px; margin-top: 40px; padding: 0;">
	  </div>	
	</div>
</div>

app/views/tanks/new.html.erb
<h1>Nuevo Aljibe</h1>

<div class="row">
  <div class="well bs-component">
    <%= form_for @tank, :html => {:class => "form-horizontal"} do |f| %>
      <fieldset>
      <%= render partial: "form", locals: {f: f} %>      
      <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <%= f.submit "Alta Aljibe", class: "btn btn-primary" %>
            <%= link_to "Volver atrás", tanks_path, class: "btn btn-default" %>
          </div>
        </div>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/tanks/show.html.erb
<div id="tankShow">
<h2><%= @tank.title %></h2>
<p>
<%= link_to "Subir foto", new_tank_photo_path(@tank) %> |
<%= link_to "Editar", edit_tank_path(@tank) %> |
<%= link_to "Borrar", @tank, method: :delete, data: {confirm: "¿Estas seguro?"} %>
</p>
<% if @tank.route %>
<h4>Ruta: <%= @tank.route%></h4> 
<% end %>
<h3>Descripción</h3>
<p id='description' data-latitude="<%= @tank.latitude %>" data-longitude="<%= @tank.longitude %>"><%= @tank.description %></p>
<% unless @tank.photos.empty? %>
<ul class="list-inline">
<% @tank.photos.each do |photo|%>
<li>
  <%= image_tag photo.image.url(:medium) %>
  <br>
  <%= link_to "Borrar foto", tank_photo_path(@tank,photo), method: :delete, data: {confirm: "¿Estas seguro?"} %>
</li>
<%end%>
</ul>
<%end%>

<div id="map-canvas" style="width: 100%; height: 400px; margin: 0; padding: 0;"></div>
</div>